/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
        poppins: ['Poppins', 'sans-serif'],
        fredoka: ['Fredoka', 'sans-serif'],
        baloo: ['"Baloo 2"', 'sans-serif'],
        quicksand: ['Quicksand', 'sans-serif'],
        lilita: ['"Lilita One"', 'sans-serif'],
        changa: ['"Changa One"', 'sans-serif'],
        rubik: ['Rubik', 'sans-serif'],
        barlow: ['Barlow', 'sans-serif'],
        nunito: ['Nunito', 'sans-serif'],
        manrope: ['Manrope', 'sans-serif'],
        lexend: ['Lexend', 'sans-serif'],
        mulish: ['Mulish', 'sans-serif'],
        urbanist: ['Urbanist', 'sans-serif'],
        titillium: ['"Titillium Web"', 'sans-serif'],
        raleway: ['Raleway', 'sans-serif'],
        archivo: ['Archivo', 'sans-serif'],
        kanit: ['Kanit', 'sans-serif'],
        prompt: ['Prompt', 'sans-serif'],
        signika: ['Signika', 'sans-serif'],
        worksans: ['"Work Sans"', 'sans-serif'],
        jost: ['Jost', 'sans-serif'],
        exo2: ['"Exo 2"', 'sans-serif'],
        asap: ['Asap', 'sans-serif'],
        bevietnam: ['"Be Vietnam Pro"', 'sans-serif'],
        hind: ['Hind', 'sans-serif'],
        cabin: ['Cabin', 'sans-serif'],
        mukta: ['Mukta', 'sans-serif'],
        fira: ['"Fira Sans"', 'sans-serif'],
        ibmplex: ['"IBM Plex Sans"', 'sans-serif'],
        merriweather: ['Merriweather', 'serif'],
        playfair: ['"Playfair Display"', 'serif'],
        lora: ['Lora', 'serif'],
        crimson: ['"Crimson Pro"', 'serif'],
        dmserif: ['"DM Serif Display"', 'serif'],
        garamond: ['"EB Garamond"', 'serif'],
        cormorant: ['"Cormorant Garamond"', 'serif'],
        notoserif: ['"Noto Serif"', 'serif'],
        sourceserif: ['"Source Serif 4"', 'serif'],
        libre: ['"Libre Baskerville"', 'serif'],

        // Modern fonts
        sora: ['Sora', 'sans-serif'],
        spacegrotesk: ['"Space Grotesk"', 'sans-serif'],
        syne: ['Syne', 'sans-serif'],
        outfit: ['Outfit', 'sans-serif'],
        bebas: ['"Bebas Neue"', 'sans-serif'],
        anton: ['Anton', 'sans-serif'],
        audiowide: ['Audiowide', 'sans-serif'],
        orbitron: ['Orbitron', 'sans-serif'],
        ptsans: ['"PT Sans"', 'sans-serif'],
        publicsans: ['"Public Sans"', 'sans-serif'],
      },
      height: {
        '200': '50rem',
        '250': '62.5rem',
        '300': '75rem',
        '350': '87.5rem',
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
        '7xl': ['4.5rem', { lineHeight: '1' }],
        '8xl': ['6rem', { lineHeight: '1' }],
        '9xl': ['8rem', { lineHeight: '1' }],
      },
    },
  },
  plugins: [],
};